services:
  db:
    image: postgres:13
    container_name: django_polls_db
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=PollsDB
      - POSTGRES_USER=PollsUser
      - POSTGRES_PASSWORD=PollsPass
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U PollsUser -d PollsDB"]
      interval: 3s
      timeout: 3s
      retries: 5
  
  polls:
    container_name: django_polls_tutorial
    build: ./tutorial
    ports:
      - "8000:8000"
    volumes:
      - staticfiles:/app/staticfiles
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://PollsUser:PollsPass@db:5432/PollsDB

  nginx:
    container_name: django_polls_nginx
    build: ./nginx
    volumes:
      - staticfiles:/static
    ports:
      - "80:80"
    depends_on:
      - polls

volumes:
  db_data:
  staticfiles: